/**
 * tests/unit/setup.ts
 *
 * Vitest セットアップファイル。
 * Vite 固有の import.meta.glob をモックし、ユニットテストで実行可能にする。
 * また、テストに必要な最小限の GAME_CONFIG データを提供する。
 */

// テスト用の最小限な config モジュールデータ
// loadConfigFromGlob が正しく動作するために { section, ...fields } 形式が必要
const mockConfigModules: Record<string, { default: Record<string, unknown> }> = {
  './config/throw.json': {
    default: {
      section: 'throw',
      gravity: 800,
      maxPower: 1400,
      airFriction: 0.995,
      powerDistanceDivisor: 200,
      speedMultiplier: 5,
      outOfBoundsRight: 2400,
      outOfBoundsLeft: -200,
      landingMargin: 100,
    },
  },
  './config/score.json': {
    default: {
      section: 'score',
      defaultColorTouchScore: 10,
      distanceScoreRate: 0.1,
      longAirScoreRate: 0.5,
    },
  },
  './config/game_balance.json': {
    default: {
      section: 'game_balance',
      scoreRatioPlay: 0.7,
      scoreRatioThrow: 0.3,
      throwScoreWeightsAirTime: 0.5,
      throwScoreWeightsArcHeight: 0.4,
      throwScoreWeightsSpeedPenalty: 0.1,
      baseScrollSpeed: 3,
      hazardSpawnBaseInterval: 60,
      hazardSpawnMinInterval: 20,
      hazardSpawnDecayRate: 0.98,
      distanceAccelMaxBonus: 0.5,
      distanceAccelFullDist: 3000,
      maxRounds: 4,
      genreLockedBoostMult: 1.5,
      genreLockedBoostDurationMs: 3000,
      defaultFallbackGenre: 'base',
    },
  },
  './config/physics.json': {
    default: {
      section: 'physics',
      defaultGravity: 1600,
      defaultPlayerMaxHp: 3,
      playerWidth: 36,
      playerHeight: 52,
      jumpVelocity: -620,
      doubleJumpVelocity: -500,
      jumpCutMultiplier: 0.5,
      gravity: 1600,
      fallGravityMult: 1.5,
      runSpeed: 200,
      slowPreciseRatio: 0.4,
      landSquashDecay: 8,
      landSquashAmount: 0.15,
      coyoteFrames: 6,
      jumpBufferFrames: 8,
      playerMinX: 50,
      playerMaxXRatio: 0.7,
      airFrictionX: 0.85,
      dashSpeed: 600,
      dashDurationSec: 0.15,
      dashCooldownSec: 0.5,
      dashIframesSec: 0.1,
      wallJumpPushSpeed: 400,
    },
  },
  './config/shoot.json': {
    default: {
      section: 'shoot',
      bulletSpeed: 500,
      bulletWidth: 14,
      bulletHeight: 5,
      bulletOutOfBoundsX: 50,
      shotCooldown: 0.2,
      comboResetTime: 2,
      baseScorePerKill: 100,
      threeWaySpeedRatio: 0.8,
      threeWayYRatio: 0.3,
    },
  },
  './config/spawn.json': {
    default: {
      section: 'spawn',
      firstSpawnDist: 300,
      enemyHpAmount: 1,
      defaultFloatAmp: 0,
      airMinOffset: 100,
      airRandOffset: 80,
      floatMinOffset: 50,
      floatRandOffset: 40,
      hazardCullLeft: -100,
      hazardCullBelow: 100,
      itemCullLeft: -100,
      spawnWeightMaxDist: 3000,
      itemDropChance: 0.15,
      itemExpChance: 0.7,
      itemOffsetX: 0,
      itemGroundOffsetY: -30,
      expItemScore: 50,
      expItemExpGain: 20,
      itemPulseRate: 3,
      hazardSpawnOffsetX: 0,
    },
  },
  './config/vfx.json': {
    default: {
      section: 'vfx',
      hitShakeIntensity: 4,
      deathShakeIntensity: 12,
      shakeDecay: 8,
      deathShakeDecay: 5,
      shakeEpsilon: 0.5,
      particleGravity: 400,
      deathParticleGravity: 200,
      deathSlowMoFactor: 0.3,
      jumpParticleCount: 5,
      jumpParticleSpeedMin: 50,
      jumpParticleSpeedMax: 150,
      jumpParticleLife: 0.4,
      jumpParticleSpread: Math.PI,
      jumpParticleOffsetX: 0,
      jumpParticleColor: '#aaaaaa',
      jumpParticleSize: 3,
      landParticleCount: 8,
      landParticleSpeedMin: 30,
      landParticleSpeedMax: 100,
      landParticleLife: 0.3,
      landParticleOffsetX: 0,
      landParticleYRatio: 1,
      landParticleColor: '#888888',
      landParticleSize: 2,
      hitParticleCount: 10,
      hitParticleSpeedMin: 100,
      hitParticleSpeedMax: 300,
      hitParticleYBoost: -100,
      hitParticleLifeMin: 0.3,
      hitParticleLifeRange: 0.3,
      hitParticleSizeBase: 3,
      hitParticleSizeRange: 2,
      deathParticleCount: 30,
      deathParticleSpeedMin: 100,
      deathParticleSpeedMax: 400,
      deathParticleYBoost: -200,
      deathParticleLifeMin: 0.5,
      deathParticleLifeRange: 0.5,
      deathParticleSizeMin: 2,
      deathParticleSizeRange: 4,
      deathParticleColors: ['#ff4444', '#ff8844', '#ffcc44'],
      stretchUpX: 0.8,
      stretchUpY: 1.2,
      stretchUpThreshold: 300,
      invincibleBlinkRate: 8,
      invincibleDuration: 1.5,
      runCycleRate: 10,
      hazardPulseRate: 2,
    },
  },
  './config/camera.json': {
    default: {
      section: 'camera',
      leadOffset: 120,
      parallaxStars: 0.05,
      parallaxFar: 0.15,
      parallaxMid: 0.4,
      parallaxGround: 1,
    },
  },
  './config/background.json': {
    default: {
      section: 'background',
      groundHeight: 0.8,
      groundLineAlpha: 0.6,
      groundLineHeight: 2,
      dashLength: 8,
      dashInterval: 12,
      dashOffsetY: -2,
      dashAlpha: 0.3,
      dashHeight: 1,
      starSectorWidth: 200,
      starCountPerSector: 5,
      starSizeMin: 1,
      starSizeRange: 2,
      starAlphaMin: 0.3,
      starAlphaStep: 0.15,
      starMaxYRatio: 0.5,
      mountainStep: 60,
      mountainAlpha: 0.15,
      mountainAmp1: 40,
      mountainFreq1: 0.003,
      mountainAmp2: 25,
      mountainFreq2: 0.007,
      mountainAmp3: 15,
      mountainFreq3: 0.015,
      mountainBase: 0.6,
      buildingAlpha: 0.1,
      buildingSectorW: 150,
      buildingMinH: 30,
      buildingRandH: 60,
      buildingMinW: 20,
      buildingRandW: 40,
    },
  },
  './config/hazard_vfx.json': {
    default: {
      section: 'hazard_vfx',
      glowBlur: 8,
      pulseSpeed: 3,
      pulseAmplitude: 0.3,
      hpBarHeight: 3,
      hpBarOffsetY: -6,
      hpBarBgAlpha: 0.4,
      hpBarHighColor: '#44ff44',
      hpBarLowColor: '#ff4444',
      hpBarThreshold: 0.5,
      rectCornerRadius: 3,
      edgeHighlightLineW: 1,
      lightenTopAmount: 40,
      lightenEdgeAmount: 20,
      pillarCapOffset: 0,
      pillarCapHeight: 4,
      pillarHighlightStop: 0.3,
      pillarHighlightAmount: 30,
      diamondEdgeLineW: 1,
    },
  },
  './config/ui.json': {
    default: {
      section: 'ui',
      popupLifeSec: 1,
      popupRiseVy: -60,
      popupFont: 'bold 14px sans-serif',
      deathOverlayAlpha: 0.7,
      deathFadeSpeed: 2,
      deathTextDelayS: 0.5,
      deathTextFadeSpeed: 3,
      deathTitleFont: 'bold 36px sans-serif',
      deathSubFont: '18px sans-serif',
      deathSubTextAlpha: 0.8,
      beatMarkerAlphaDivisor: 3,
      beatMarkerMaxAlpha: 0.6,
      beatMarkerColor: '#ff4444',
      beatMarkerLineW: 2,
      beatMarkerDash: [4, 4],
    },
  },
  './config/difficulty.json': {
    default: {
      section: 'difficulty',
      updateDistancesInitial: [500, 1000, 2000, 3500, 5500],
      updateDistancesBaseInterval: 500,
      updateDistancesCount: 5,
      genreLockedPlayDist: 8000,
      tempoSpeedBonus: 0.15,
      enemyDensityRate: 0.0001,
      globalDifficultyMult: 1,
    },
  },
  './config/boss.json': {
    default: {
      section: 'boss',
      firstBossDist: 3000,
      bossRespawnDist: 2000,
      bossHp: 10,
      arenaHpBonus: 5,
      bossWidth: 60,
      bossHeight: 80,
      bossCollisionGrace: 8,
      bossSpawnShake: 10,
      bossDeathShake: 15,
      bossDeathParticles: 50,
    },
  },
  './config/rhythm_tuning.json': {
    default: {
      section: 'rhythm_tuning',
      defaultBpm: 120,
      bpmTempoBonus: 10,
      minBpm: 60,
      maxBpm: 200,
      justWindowSec: 0.08,
      justMultiplier: 3,
      goodWindowMult: 2,
      goodMultiplier: 1.5,
      beatHazardFlipChance: 0.3,
      beatSpawnBurstRate: 0.5,
      beatDashMult: 1.5,
      beatDashFrames: 6,
    },
  },
  './config/stealth.json': {
    default: {
      section: 'stealth',
      stealthAlpha: 0.3,
      stealthDurationSec: 2,
      stealthCooldownSec: 5,
      stealthSafeBonus: 50,
      detectionRange: 150,
    },
  },
  './config/genre_params.json': {
    default: {
      section: 'genre_params',
      recommendedSingleChoice: 2,
      recommendedMaxPerAxis: 6,
      thresholdGuide: {
        singleAxis: 5,
        dualAxis: 4,
        tripleAxis: 3,
      },
    },
  },
  './config/genres.json': {
    default: {
      section: 'genres',
      genres: [],
      themeColors: {},
    },
  },
};

// import.meta.glob のモック（Vite 固有機能を Node 環境で利用可能にする）
vi.stubGlobal('import.meta', {
  ...import.meta,
  glob: vi.fn(() => mockConfigModules),
  env: {
    PROD: false,
  },
})
